### ISSUE TITLE
Need to upgrade the codes

### ISSUE THREAD

**Issue by TomHsiung** [Cristian-A/Perseus#1]
I really appreciate your work but, macOS 15.2 and the Apple dictionary crashes after installation of the Latin contents. Thanks.

**Comment by cristian-5** [comment]
Thanks! I will take a look. Apple doesn't like to disclose new documentation for these things so hopes are pretty low 😞

**Comment by TomHsiung** [comment]
Looking forward to it!

**Comment by cristian-5** [comment]
Yes so clear the old stuff and follow these new instructions: download the file `Latin.dictionary.zip` from [releases](https://github.com/cristian-5/Perseus/releases) and unzip it inside the folder `~/Library/Dictionaries/`. I'm using this on my computer and it works with the latest operating system with the latest Dictionary app. Let me know if it still gives you problems.

**Comment by TomHsiung** [comment]
Hmmm, it works on my macOS Sequoia 15.2 now. I really appreciate your improvement, sir. Thank for a bunch. Haha, now I can enjoy the learning of Latina!
